name: Chatwurx
favicon: null
layout_spectrum: 0.74855
typography_spectrum: 0.99904
title: CHATWURX
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfbf6'
    - '#06050a'
    - '#38323e'
    - '#cfceba'
    - '#a8a390'
  brandStrength: 0.5
  lightness: 0.7231614571064711
  saturation: 0.749224858591333
  rhythmicContrast: 0.6680322121828794
purpose: []
